### ISSUE TITLE
question

### ISSUE THREAD

**Issue by drzhang3** [RobertLexis/CloudSimPy#2]
您好，想问下，您的job中的task是不是没有包含有**依赖关系**啊？
测试文件**job.csv**好像是基于**历史数据**？不知道您的数据来自哪里？

**Comment by FC-Li** [comment]
+ 目前确实并没有考虑 job 中 task 的 DAG。
+ 历史数据是阿里巴巴集群的数据 https://github.com/alibaba/clusterdata/tree/master/cluster-trace-v2017

**Comment by silkyrose** [comment]
Hello Robert
我试着对了下您的job.cvs数据和阿里的2017年cluster数据，可是完全对不上啊。不知道您是用什么办法生成的这份数据？
