### ISSUE TITLE
Cannot import the core module

### ISSUE THREAD

**Issue by swainsubrat** [RobertLexis/CloudSimPy#5]
Couldn't import the core file while running the main-makespan.py file

Traceback (most recent call last):
  File "main-makespan.py", line 10, in <module>
    from core.machine import MachineConfig
ModuleNotFoundError: No module named 'core'

**Comment by wenwenlin** [comment]
> Couldn't import the core file while running the main-makespan.py file
> 
> Traceback (most recent call last):
> File "main-makespan.py", line 10, in
> from core.machine import MachineConfig
> ModuleNotFoundError: No module named 'core'

add environment variable
